version: '3.8'

services:
  realm-quest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realm-quest-rpg
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - coolify
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "coolify.managed=true"
      - "coolify.name=realm-quest"
      - "coolify.type=application"
